import { CustomerInfoType } from "./customerInfo";
import { UpsellInfoType } from "./upsellInfo";

export type SessionDataType = {
  billingId?: string;
  campaignId: string;
  clarity_id: string;
  clickId: string;
  client_id?: string;
  createdAt: string;
  currentStep: string;
  customFields?: {
    [key: string]: string;
  };
  customerInfo: CustomerInfoType;
  fb_browser_id: string;
  fb_click_id: string;
  ff_hitid: string;
  ff_vid: string;
  finalizedAt?: string;
  finalizedBy?: string;
  finalizationAttempts?: number;
  funnel: string;
  ga_experiment: string;
  ipAddress: string;
  mixpanel_id: string;
  notes: string;
  orderConfirmed: boolean;
  orderConfirmedAt: string;
  orderData?: {
    authId?: string;
    customerId?: string;
    error_found?: string;
    gatewayCustomerService?: string;
    gatewayDescriptor?: string;
    gateway_id?: string;
    orderSalesTaxAmount?: string;
    orderSalesTaxPercent?: string;
    orderTotal?: string;
    order_id?: string;
    prepaid_match?: string;
    resp_msg?: string;
    response_code?: string;
    transactionID?: string;
  };
  orderFinalized: boolean;
  orderSuccess?: string;
  paymentType: string;
  paypalOrder?: {
    ACS?: string;
    alt_pay_method?: string;
    customerId?: string;
    errorFound?: string;
    gatewayCustomerService?: string;
    gatewayDescriptor?: string;
    gatewayId?: string;
    orderId: string;
    orderSalesTaxAmount?: string;
    orderSalesTaxPercent?: string;
    orderTotal?: string;
    prepaid_match?: string;
    responseCode?: string;
  };
  preAuthData?: {
    authId?: string;
    error_found?: string;
    error_message?: string;
    expiry_date?: string;
    gateway_id?: string;
    prepaid?: string;
    prepaid_match?: string;
    response_code?: string;
    temp_customer_id?: string;
    transactionID?: string;
  };
  preAuthSuccess?: boolean;
  product: number;
  productId: string;
  productName: string;
  productOfferId: string;
  productPrice: string;
  productShipping: string;
  productShippingId: string;
  shopifyData?: any;
  source_url?: string;
  stickyCustomerId?: string;
  total: string;
  updatedAt: string;
  upsellOrderData?: {
    customerId?: string;
    error_found?: string;
    gatewayCustomerService?: string;
    gatewayDescriptor?: string;
    gateway_id?: string;
    orderSalesTaxAmount?: string;
    orderSalesTaxPercent?: string;
    orderTotal?: string;
    order_id?: string;
    prepaid_match?: string;
    response_code?: string;
    transactionID?: string;
  };
  upsells: UpsellInfoType[];
  urlParams?: {
    [key: string]: string;
  };
  userAgent: string;
  vwo_uuid: string;
};
